version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app_music_churn_ml
    file_exists_behavior: OVERWRITE

hooks:

  ApplicationStop:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root
