version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
   -location: scripts/stop_containers.sh
   timeout: 300
   runas: root

BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root

ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root

ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

AfterInstall:
   -location: scripts/start_containers.sh
   timeout: 300
   runas: root
  
