version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /ml/docker-credential/username
    DOCKER_REGISTRY_PASSWORD: /ml/docker-credential/password
    DOCKER_REGISTRY_URL: /ml/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r dockerrequirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/musicstreaming-customerretention-prediction-ml:aws_prod_v1" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/musicstreaming-customerretention-prediction-ml:aws_prod_v1"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'

